### ISSUE TITLE
Problems with using Rscala with Scala 2.10

### ISSUE THREAD

**Issue by raproth** [dbdahl/rscala#4] opened 2017-08-04 11:19 UTC
In Scala 2.11 ()using rscala 2.2.2)  I can write somthing like this:

```
org.ddahl.rscala.RClient()
R.x = 1.0
```

With Scala 2.10 this gives me a compilation error:

```
Error:(8, 5) type mismatch;
 found   : R.type (with underlying type org.ddahl.rscala.RClient)
 required: ?{def x: ?}
Note that implicit conversions are not applicable because they are ambiguous:
 both method any2Ensuring in object Predef of type [A](x: A)Ensuring[A]
 and method any2ArrowAssoc in object Predef of type [A](x: A)ArrowAssoc[A]
 are possible conversion functions from R.type to ?{def x: ?}
    R.x = 1.0
```

Is there a way to make this work, or should I use `R.set("x",1.0)` ?

**Comment by dbdahl** [comment] 2017-08-04 15:09
rscala on Scala 2.10 is not as well tested as it is on Scala 2.12, so I can believe there may be a problem. 
 Nevetheless, I cannot reproduce the error on my Ubuntu 16.04 machine running Java(TM) SE Runtime Environment (build 1.8.0_112-b15).  See the transcript below:

> $ cat test.sc 
> val R = org.ddahl.rscala.RClient()
> 
> R.x = 10
> println(R.x)
> 
> $ ~/local/scala/scala/scala-2.10.6/bin/scala -cp /home/dahl/local/R/3.4.0-shlib/lib/R/library/rscala/java/scala-2.10/rscala_2.10-2.2.2.jar test.sc 
> (10,Int)
> 
> $ ~/local/scala/scala/scala-2.11.11/bin/scala -cp /home/dahl/local/R/3.4.0-shlib/lib/R/library/rscala/java/scala-2.11/rscala_2.11-2.2.2.jar test.sc 
> (10,Int)
> 
> $ ~/local/scala/scala/scala-2.12.3/bin/scala -cp scala-2.12/rscala_2.12-2.3.0-SNAPSHOT.jar test.sc (10,Int)
> 

Can you please provide details of your platform and a working example to help me reproduce the problem?

**Comment by dbdahl** [comment] 2017-08-08 14:33
I am able to confirm the problem.  That is, the following does not work on Scala 2.10 and does work on Scala 2.11 and 2.12:

```
val R = org.ddahl.rscala.RClient()
R.x = 10
```

But, the following does work on Scala 2.10, 2.11, and 2.12:

```
val R = org.ddahl.rscala.RClient()
R.set("x",10)
```

This appears to be a bug in Scala 2.10 itself and, since Scala 2.10 is no longer maintained, I do not anticipate it will be fixed.  I also don't see a work-around that rscala can provide except to recommend the "set" and "get" methods when using Scala 2.10.

Thanks for the report.

**Closed as completed by dbdahl** 2017-08-08 14:33 UTC
